name: Bug Report
description: Report something not working
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is happening?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step reproduction
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
